name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCIDoGSUVBBE9kfXawsvJyQA"
          max_post_count: 3
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "d.mm.yyyy, hh:mm"
          template: '<table align="center"><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
